import {
  IconAdjustmentsHorizontal,
  IconAirConditioning,
  IconAlertCircle,
  IconApple,
  IconArmchair,
  IconArrowsExchange,
  IconAtom,
  IconBabyCarriage,
  IconBackpack,
  IconBallBasketball,
  IconBallFootball,
  IconBarbell,
  IconBasket,
  IconBeach,
  IconBed,
  IconBeer,
  IconBike,
  IconBolt,
  IconBook,
  IconBook2,
  IconBookmark,
  IconBooks,
  IconBottle,
  IconBrandNetflix,
  IconBrandSpotify,
  IconBread,
  IconBriefcase,
  IconBuilding,
  IconBuildingBank,
  IconBuildingSkyscraper,
  IconBulb,
  IconBurger,
  IconBus,
  IconBusinessplan,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconCandy,
  IconCar,
  IconCarGarage,
  IconCarSuv,
  IconCarrot,
  IconCash,
  IconCat,
  IconCategory,
  IconCertificate,
  IconChartLine,
  IconChefHat,
  IconClock,
  IconCloud,
  IconCoffee,
  IconCoin,
  IconCoins,
  IconConfetti,
  IconCookie,
  IconCreditCard,
  IconCup,
  IconCut,
  IconDental,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceSim,
  IconDeviceTv,
  IconDeviceTvOld,
  IconDiamond,
  IconDog,
  IconDots,
  IconDroplet,
  IconEgg,
  IconEyeCheck,
  IconEyeglass,
  IconFileInvoice,
  IconFileText,
  IconFirstAidKit,
  IconFish,
  IconFlag,
  IconFlame,
  IconFridge,
  IconFriends,
  IconGasStation,
  IconGift,
  IconGlassFull,
  IconHammer,
  IconHanger,
  IconHeadphones,
  IconHeart,
  IconHeartbeat,
  IconHome,
  IconHospital,
  IconIceCream,
  IconId,
  IconKey,
  IconLamp,
  IconLanguage,
  IconLock,
  IconLuggage,
  IconMail,
  IconMap,
  IconMapPin,
  IconMasksTheater,
  IconMassage,
  IconMeat,
  IconMicrophone2,
  IconMilk,
  IconMotorbike,
  IconMountain,
  IconMovie,
  IconMusic,
  IconNotebook,
  IconPackage,
  IconPaint,
  IconPalette,
  IconParking,
  IconPaw,
  IconPencil,
  IconPercentage,
  IconPhone,
  IconPigMoney,
  IconPill,
  IconPizza,
  IconPlane,
  IconPlant,
  IconPlug,
  IconPuzzle,
  IconQuestionMark,
  IconReceipt,
  IconReceiptTax,
  IconReportMoney,
  IconRoad,
  IconRoute,
  IconRun,
  IconSalad,
  IconSchool,
  IconScissors,
  IconScooter,
  IconServer,
  IconShieldCheck,
  IconShip,
  IconShirt,
  IconShoe,
  IconShoppingBag,
  IconShoppingCart,
  IconSofa,
  IconSoup,
  IconStar,
  IconSteeringWheel,
  IconStethoscope,
  IconTag,
  IconTent,
  IconTicket,
  IconTool,
  IconToolsKitchen2,
  IconTrain,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTruckDelivery,
  IconUmbrella,
  IconUser,
  IconUsers,
  IconVaccine,
  IconWallet,
  IconWashMachine,
  IconWifi,
  IconWorld,
  IconYoga,
  type Icon,
} from "@tabler/icons-react";

/**
 * Iconos de categoría (Tabler). Se guarda el nombre en kebab-case de Tabler,
 * p. ej. "shopping-cart". Es una selección curada en lugar de los miles de
 * Tabler: así el selector se puede recorrer y el bundle no carga todos.
 */
export const CATEGORY_ICON_GROUPS: { label: string; icons: string[] }[] = [
  {
    label: "Comida y bebida",
    icons: [
      "tools-kitchen-2",
      "shopping-cart",
      "basket",
      "burger",
      "pizza",
      "coffee",
      "cup",
      "beer",
      "glass-full",
      "bread",
      "apple",
      "carrot",
      "meat",
      "fish",
      "ice-cream",
      "candy",
      "cookie",
      "salad",
      "soup",
      "egg",
      "milk",
      "bottle",
      "chef-hat",
    ],
  },
  {
    label: "Transporte",
    icons: [
      "car",
      "car-suv",
      "gas-station",
      "bus",
      "train",
      "plane",
      "motorbike",
      "bike",
      "scooter",
      "ship",
      "parking",
      "road",
      "tool",
      "steering-wheel",
      "car-garage",
      "map-pin",
      "route",
    ],
  },
  {
    label: "Hogar",
    icons: [
      "home",
      "building",
      "bed",
      "sofa",
      "armchair",
      "lamp",
      "bulb",
      "plug",
      "bolt",
      "droplet",
      "flame",
      "wifi",
      "device-tv",
      "air-conditioning",
      "wash-machine",
      "fridge",
      "hammer",
      "paint",
      "plant",
      "key",
      "trash",
    ],
  },
  {
    label: "Salud",
    icons: [
      "heartbeat",
      "heart",
      "stethoscope",
      "pill",
      "vaccine",
      "first-aid-kit",
      "dental",
      "eye-check",
      "hospital",
      "barbell",
      "run",
      "yoga",
      "massage",
    ],
  },
  {
    label: "Compras",
    icons: [
      "shopping-bag",
      "shirt",
      "shoe",
      "hanger",
      "diamond",
      "eyeglass",
      "device-laptop",
      "device-mobile",
      "headphones",
      "device-gamepad-2",
      "camera",
      "gift",
      "tag",
      "package",
      "truck-delivery",
    ],
  },
  {
    label: "Entretenimiento",
    icons: [
      "movie",
      "device-tv-old",
      "music",
      "ticket",
      "confetti",
      "ball-football",
      "ball-basketball",
      "palette",
      "book",
      "books",
      "puzzle",
      "brand-netflix",
      "brand-spotify",
      "microphone-2",
      "masks-theater",
    ],
  },
  {
    label: "Educación",
    icons: [
      "school",
      "book-2",
      "notebook",
      "pencil",
      "backpack",
      "certificate",
      "language",
      "atom",
    ],
  },
  {
    label: "Finanzas",
    icons: [
      "wallet",
      "cash",
      "coin",
      "coins",
      "credit-card",
      "building-bank",
      "pig-money",
      "receipt",
      "receipt-tax",
      "file-invoice",
      "report-money",
      "chart-line",
      "trending-up",
      "trending-down",
      "percentage",
      "briefcase",
      "businessplan",
      "calculator",
      "lock",
      "adjustments-horizontal",
      "arrows-exchange",
    ],
  },
  {
    label: "Personas y mascotas",
    icons: [
      "user",
      "users",
      "baby-carriage",
      "friends",
      "paw",
      "dog",
      "cat",
      "cut",
      "scissors",
    ],
  },
  {
    label: "Viajes",
    icons: [
      "luggage",
      "beach",
      "mountain",
      "tent",
      "world",
      "map",
      "id",
      "building-skyscraper",
    ],
  },
  {
    label: "Servicios",
    icons: [
      "phone",
      "device-sim",
      "cloud",
      "server",
      "shield-check",
      "umbrella",
      "file-text",
      "mail",
    ],
  },
  {
    label: "Otros",
    icons: [
      "dots",
      "category",
      "star",
      "bookmark",
      "flag",
      "calendar",
      "clock",
      "alert-circle",
      "question-mark",
    ],
  },
];

export const CATEGORY_ICONS: Record<string, Icon> = {
  "tools-kitchen-2": IconToolsKitchen2,
  "shopping-cart": IconShoppingCart,
  "basket": IconBasket,
  "burger": IconBurger,
  "pizza": IconPizza,
  "coffee": IconCoffee,
  "cup": IconCup,
  "beer": IconBeer,
  "glass-full": IconGlassFull,
  "bread": IconBread,
  "apple": IconApple,
  "carrot": IconCarrot,
  "meat": IconMeat,
  "fish": IconFish,
  "ice-cream": IconIceCream,
  "candy": IconCandy,
  "cookie": IconCookie,
  "salad": IconSalad,
  "soup": IconSoup,
  "egg": IconEgg,
  "milk": IconMilk,
  "bottle": IconBottle,
  "chef-hat": IconChefHat,
  "car": IconCar,
  "car-suv": IconCarSuv,
  "gas-station": IconGasStation,
  "bus": IconBus,
  "train": IconTrain,
  "plane": IconPlane,
  "motorbike": IconMotorbike,
  "bike": IconBike,
  "scooter": IconScooter,
  "ship": IconShip,
  "parking": IconParking,
  "road": IconRoad,
  "tool": IconTool,
  "steering-wheel": IconSteeringWheel,
  "car-garage": IconCarGarage,
  "map-pin": IconMapPin,
  "route": IconRoute,
  "home": IconHome,
  "building": IconBuilding,
  "bed": IconBed,
  "sofa": IconSofa,
  "armchair": IconArmchair,
  "lamp": IconLamp,
  "bulb": IconBulb,
  "plug": IconPlug,
  "bolt": IconBolt,
  "droplet": IconDroplet,
  "flame": IconFlame,
  "wifi": IconWifi,
  "device-tv": IconDeviceTv,
  "air-conditioning": IconAirConditioning,
  "wash-machine": IconWashMachine,
  "fridge": IconFridge,
  "hammer": IconHammer,
  "paint": IconPaint,
  "plant": IconPlant,
  "key": IconKey,
  "trash": IconTrash,
  "heartbeat": IconHeartbeat,
  "heart": IconHeart,
  "stethoscope": IconStethoscope,
  "pill": IconPill,
  "vaccine": IconVaccine,
  "first-aid-kit": IconFirstAidKit,
  "dental": IconDental,
  "eye-check": IconEyeCheck,
  "hospital": IconHospital,
  "barbell": IconBarbell,
  "run": IconRun,
  "yoga": IconYoga,
  "massage": IconMassage,
  "shopping-bag": IconShoppingBag,
  "shirt": IconShirt,
  "shoe": IconShoe,
  "hanger": IconHanger,
  "diamond": IconDiamond,
  "eyeglass": IconEyeglass,
  "device-laptop": IconDeviceLaptop,
  "device-mobile": IconDeviceMobile,
  "headphones": IconHeadphones,
  "device-gamepad-2": IconDeviceGamepad2,
  "camera": IconCamera,
  "gift": IconGift,
  "tag": IconTag,
  "package": IconPackage,
  "truck-delivery": IconTruckDelivery,
  "movie": IconMovie,
  "device-tv-old": IconDeviceTvOld,
  "music": IconMusic,
  "ticket": IconTicket,
  "confetti": IconConfetti,
  "ball-football": IconBallFootball,
  "ball-basketball": IconBallBasketball,
  "palette": IconPalette,
  "book": IconBook,
  "books": IconBooks,
  "puzzle": IconPuzzle,
  "brand-netflix": IconBrandNetflix,
  "brand-spotify": IconBrandSpotify,
  "microphone-2": IconMicrophone2,
  "masks-theater": IconMasksTheater,
  "school": IconSchool,
  "book-2": IconBook2,
  "notebook": IconNotebook,
  "pencil": IconPencil,
  "backpack": IconBackpack,
  "certificate": IconCertificate,
  "language": IconLanguage,
  "atom": IconAtom,
  "wallet": IconWallet,
  "cash": IconCash,
  "coin": IconCoin,
  "coins": IconCoins,
  "credit-card": IconCreditCard,
  "building-bank": IconBuildingBank,
  "pig-money": IconPigMoney,
  "receipt": IconReceipt,
  "receipt-tax": IconReceiptTax,
  "file-invoice": IconFileInvoice,
  "report-money": IconReportMoney,
  "chart-line": IconChartLine,
  "trending-up": IconTrendingUp,
  "trending-down": IconTrendingDown,
  "percentage": IconPercentage,
  "briefcase": IconBriefcase,
  "businessplan": IconBusinessplan,
  "calculator": IconCalculator,
  "lock": IconLock,
  "adjustments-horizontal": IconAdjustmentsHorizontal,
  "arrows-exchange": IconArrowsExchange,
  "user": IconUser,
  "users": IconUsers,
  "baby-carriage": IconBabyCarriage,
  "friends": IconFriends,
  "paw": IconPaw,
  "dog": IconDog,
  "cat": IconCat,
  "cut": IconCut,
  "scissors": IconScissors,
  "luggage": IconLuggage,
  "beach": IconBeach,
  "mountain": IconMountain,
  "tent": IconTent,
  "world": IconWorld,
  "map": IconMap,
  "id": IconId,
  "building-skyscraper": IconBuildingSkyscraper,
  "phone": IconPhone,
  "device-sim": IconDeviceSim,
  "cloud": IconCloud,
  "server": IconServer,
  "shield-check": IconShieldCheck,
  "umbrella": IconUmbrella,
  "file-text": IconFileText,
  "mail": IconMail,
  "dots": IconDots,
  "category": IconCategory,
  "star": IconStar,
  "bookmark": IconBookmark,
  "flag": IconFlag,
  "calendar": IconCalendar,
  "clock": IconClock,
  "alert-circle": IconAlertCircle,
  "question-mark": IconQuestionMark,
};

export function isCategoryIcon(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(CATEGORY_ICONS, name);
}

/** Nombres de lucide que se usaban antes de pasar a Tabler (respaldos viejos) */
const LEGACY_ICONS: Record<string, string> = {
  Utensils: "tools-kitchen-2",
  Car: "car",
  Home: "home",
  Film: "movie",
  Heart: "heartbeat",
  ShoppingBag: "shopping-bag",
  GraduationCap: "school",
  Receipt: "receipt",
  Briefcase: "briefcase",
  TrendingUp: "trending-up",
  Circle: "dots",
  SlidersHorizontal: "adjustments-horizontal",
};

/** Icono válido de Tabler para guardar, traduciendo los viejos; si no, null */
export function normalizeCategoryIcon(name: string | null | undefined): string | null {
  if (!name) return null;
  if (isCategoryIcon(name)) return name;
  return LEGACY_ICONS[name] ?? null;
}
